name: 'Reusable Database and App Backup'
description: 'Backup database and application directory, then upload to AWS S3 or save locally'
inputs:
  db_name:
    description: 'Database name'
    required: true
  db_user:
    description: 'Database user'
    required: true
  db_password:
    description: 'Database password'
    required: true
  db_host:
    description: 'Database host'
    required: true
  app_dir:
    description: 'Application directory path'
    required: true
  backup_dir:
    description: 'Backup directory path'
    required: true
  s3_bucket:
    description: 'AWS S3 bucket name (required if using S3)'
    required: false
  s3_region:
    description: 'AWS S3 Region (required if using S3)'
    required: false
  backup_destination:
    description: 'Backup destination ("s3" for AWS S3, "local" for local storage)'
    required: true
    default: 'local'
runs:
  using: 'docker'
  image: 'Dockerfile'
